---
- name: install required packages
  package:
    name: "{{ item }}"
    state: present
  loop:
    - yum-utils
    - device-mapper-persistent-data
    - lvm2

- name: add docker yum repo
  yum_repository:
    name: docker-ce-stable
    description: 'Docker CE Stable - $basearch'
    baseurl: 'https://download.docker.com/linux/centos/7/$basearch/stable'
    enabled: true
    gpgcheck: true
    gpgkey: https://download.docker.com/linux/centos/gpg

- name: install docker
  package:
    name: "{{ rke_docker_package_name }}"

- name: ensure docker is started
  service:
    name: docker
    state: started
    enabled: true

- name: add rancher user to docker group
  user:
    name: "{{ rke_user }}"
    append: yes
    groups: docker
