---
# tasks file for ansible-role-rke

# install rke requirements
- include: requirements.yml

# install rke
- include: rke.yml

# configure storage class
- include: storage-class.yml
  when: rke_storage_class is defined
